config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="empresa:business-list"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('i18n/', include('django.conf.urls.i18n')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lab_ati.users.urls", namespace="users")), 
    path("proveedor/", include("lab_ati.proveedor.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("business/", include("lab_ati.cliente.urls")),
    # Business urls
    path("business/", include("lab_ati.empresa.urls", namespace="business")),
    # Employee urls

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    #path('proveedor/crear', createProveedor, name='createProveedor')
    
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lab_ati/cliente/urls.py
from django.urls import path
from lab_ati.cliente.views import (
    clientes,
    ver_cliente,
    crear_cliente,
    eliminar_cliente, 
    editar_cliente
    )

urlpatterns = [
    path('<slug:business_id>/clients/', clientes, name='clients'),
    path('<slug:business_id>/clients/create', crear_cliente, name='create-client'),
    path('<slug:business_id>/clients/<slug:id>', ver_cliente, name='detail-client'),
    path('<slug:business_id>/clients/delete/<slug:id>', eliminar_cliente, name='delete-client'),
    path('<slug:business_id>/clients/edit/<slug:id>', editar_cliente, name='edit-client')
]

lab_ati/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path("", views.BusinessListView.as_view(), name="business-list"),
    path("create", views.CreateBusinessView.as_view(), name="create-business"),
    path("details/<slug:pk>", views.BusinessDetailsView.as_view(), name="business-details"),
    path("edit/<slug:pk>", views.EditBusinessView.as_view(), name="edit-business"),
    path("delete/<slug:pk>", views.DeleteBusinessView.as_view(), name="delete-business"),
    path("<slug:business_id>/employees/create", views.CreateEmployeeView.as_view(), name="create-employee"),
    path("<slug:business_id>/employees/edit/<slug:pk>", views.EditEmployeeView.as_view(), name="edit-employee"),
    path("<slug:business_id>/employees/", views.ListEmployeeView.as_view(), name="list-employee"),
    path("<slug:business_id>/employees/delete/<slug:pk>", views.DeleteEmployeeView.as_view(), name="delete-employee"),
    path("<slug:business_id>/employees/<slug:pk>", views.DetailEmployeeView.as_view(), name="detail-employee"),
]

lab_ati/users/urls.py
from django.urls import path

from lab_ati.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lab_ati/cliente/models.py
from django.db import models
from lab_ati.empresa.models import DirABC
from django.utils.translation import gettext_lazy as _

# Create your models here.

class ClientType(models.TextChoices):
    LABORA_EMPRESA = 'LE', _('Labora empresa')
    STUDENT = 'SO', _('Estudiante')
    OTHER = 'JR', _('Otro')

class Cliente(DirABC):

    nombre = models.TextField(_("Nombre y Apellido"))
    tipo = models.TextField(
        choices=ClientType.choices,
    )
    empcompany=models.TextField(_("Compañia/Organismo"))
    cargo=models.TextField(_("Cargo"))
    empresa=models.ForeignKey(
        to="empresa.Empresa",
        on_delete=models.CASCADE,
        related_name="clientes",
        verbose_name=_("Empresa"),
        null=True,
        blank=True,
    )
    personal_email=models.TextField(_("Email personal"))
    tlf_celular=models.TextField(_("Teléfono celular"))
    whatsapp=models.TextField(_("Whatsapp"))
    servicio_ofrecido = models.TextField(_("Servicio ofrecido"))
    curso_interes=models.TextField(_("Curso de interés"))
    frecuencia=models.TextField(_("Frecuencia con la que desea mantenerse informado"))

    def __str__(self):
        return f"{self.nombre} {self.tipo}"

lab_ati/cliente/forms.py
from django import forms
from lab_ati.cliente.models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

lab_ati/proveedor/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
  class Meta:
    model = Proveedor
    fields = '__all__'
 

lab_ati/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lab_ati.cliente.models import Cliente
from lab_ati.cliente.forms import ClienteForm
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.empresa.models import SocialMedia
from lab_ati.utils.social_media import add_social_media
from django.urls import reverse

def clientes(request, business_id):
    context = {}
    context['business_id'] = business_id
    clientes = Cliente.objects.filter(empresa__id__contains = business_id)
    context['clientes'] = clientes
    return render(request, 'pages/clientes/index.html', context)

def ver_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    context['form'] = ClienteForm(request.POST or None, instance=cliente)
    context['social_medias'] = cliente.redes_sociales.all()
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    return render(request, 'pages/clientes/verCliente.html', context)

def crear_cliente(request, business_id):
    context = {}
    context['business_id'] = business_id
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST)
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)
        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return render(request, 'pages/clientes/crear.html', context)


def eliminar_cliente(request, id, business_id):
    cliente = Cliente.objects.get(id = id)
    cliente.delete()
    context = {}
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return redirect('clients', business_id = business_id)

def editar_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid() and request.POST:
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST, queryset=savedForm.redes_sociales.all())
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)

        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=cliente.redes_sociales.all())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context["editing_social"] = True

    return render(request, 'pages/clientes/editar.html', context)

lab_ati/proveedor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Proveedor
from .forms import ProveedorForm
#from ..empresa.models import Empresa, SocialMedia 
from django.template.defaulttags import register
from lab_ati.empresa.models import Empresa, SocialMedia
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.utils.social_media import add_social_media

@register.filter
def get_item(objectList, key):
  if objectList == "":
    return ""
  return getattr(objectList,key)

def createProveedor(request):
  if request.method == 'GET': 
    empresaId = request.GET.get('empresa') 
    if(empresaId == None):
      return render(request,'404.html')
    empresa = Empresa.objects.get(id=empresaId)
    if(empresa == None):
      return render(request,'404.html')
    #print(empresa)
    formularioProveedor = ProveedorForm(request.GET)
    context = {}
    proveedorSocialMedia = SocialMediaFormset(
        prefix="proveedorSocial",
        queryset=SocialMedia.objects.none()
    )
    socialMediaRepresentanteForm = SocialMediaFormset(
        queryset=SocialMedia.objects.none(),
        prefix="representanteSocial"
    )
    #socialMediaRepresentanteForm = SocialMediaFormset(queryset=SocialMedia.objects.none())
    #print(proveedorSocialMedia)
    context = {
      "data":{
        "empresa":empresa,
        "update":False, 
        "formulario":formularioProveedor,
        "socialMedia" : proveedorSocialMedia,
        "socialMediaRepresentante": socialMediaRepresentanteForm
      },
      "list_link":'/proveedor?empresa='+str(empresaId)
      }
    return render(request,'pages/proveedor/create-update.html', context)

  elif request.method == 'POST':
    empresaId = request.GET.get('empresa') 
    if(empresaId == None):
      return render(request,'404.html')  
    empresa = Empresa.objects.get(id=empresaId)
    if(empresa == None):
      return render(request,'404.html')
    formularioProveedor = ProveedorForm(request.POST)
    #print(formularioProveedor)
    social_media_formset = SocialMediaFormset(data=request.POST, prefix="proveedorSocial")
    redes_representante_formset = SocialMediaFormset(data=request.POST, prefix="representanteSocial")
    #print(social_media_formset)
    if formularioProveedor.is_valid() and social_media_formset.is_valid() and redes_representante_formset.is_valid():
      #print('is valid!')
      proveedorSaved = formularioProveedor.save()
      # Añadir las redes sociales del proveedor
      add_social_media(proveedorSaved,social_media_formset, belongs_to="redes_proveedor")
      # Añadir las redes sociales del representante
      add_social_media(proveedorSaved, redes_representante_formset, belongs_to="redes_representante")
      return redirect('/proveedor?empresa='+empresaId)
    return redirect('/proveedor/crear?empresa='+empresaId)
    
def updateProveedor(request):
  if request.method == 'GET':
    proveedorId = request.GET.get('proveedor')
    print('proveedor id: ', proveedorId)
    if(proveedorId == None):
      return render(request,'404.html')
    proveedor = Proveedor.objects.get(id=proveedorId)
    if(proveedor == None):
      return render(request,'404.html') 
    print(proveedor)
    formularioProveedor = ProveedorForm(request.POST or request.GET)
    socialMediaForm  = SocialMediaFormset(
        prefix="proveedorSocial",
        queryset=proveedor.redes_proveedor.all()
    )
    socialMediaRepresentanteForm = SocialMediaFormset(
        prefix="representanteSocial",
        queryset=proveedor.redes_representante.all(),
    )

    context = {
      "business_id": proveedor.empresa.id,
      "data":{
        "proveedor":proveedor,
        "empresa":{"id":proveedor.empresa.id},
        "update":True,
        "formulario":formularioProveedor,
        "socialMedia":socialMediaForm,
        "socialMediaRepresentante": socialMediaRepresentanteForm
      },
      "editing_social":True,
      "list_link":'/proveedor?empresa='+str(proveedor.empresa.id)
    }
    return render(request,'pages/proveedor/create-update.html',context)
  elif request.method == 'POST':
    proveedorId = request.GET.get('proveedor')
    print('proveedor id: ', proveedorId)
    if(proveedorId == None):
      return render(request,'404.html')
    oldProveedor = Proveedor.objects.get(id=proveedorId)
    if(oldProveedor == None):
      return render(request,'404.html')
    print(oldProveedor)
    formularioProveedor = ProveedorForm(request.POST, instance=oldProveedor)
    print(formularioProveedor)
    empresaId = str(oldProveedor.empresa.id)
    if formularioProveedor.is_valid():
      print('is valid!')
      proveedorSaved = formularioProveedor.save()
      social_media_formset = SocialMediaFormset(
        prefix="proveedorSocial",
        data=request.POST,
        queryset=proveedorSaved.redes_proveedor.all()
      )
      socialMediaRepresentanteForm = SocialMediaFormset(
        queryset=proveedorSaved.redes_representante.all(),
        data=request.POST,
        prefix="representanteSocial"
      )

      if social_media_formset.is_valid():
        add_social_media(proveedorSaved,social_media_formset, belongs_to="redes_proveedor")
      if socialMediaRepresentanteForm.is_valid():
        add_social_media(proveedorSaved,socialMediaRepresentanteForm, belongs_to="redes_representante")
    return redirect('/proveedor?empresa='+empresaId)


#listar proeedores de una emrpresa dada
def listProveedor(request):
  empresaId = request.GET.get('empresa')
  print(empresaId)
  if(empresaId == None):
    return render(request,'pages/404.html')

  empresa = findEmpresa(empresaId)
  print(empresa)
  if(empresa == None): #empresa no existe
    return render(request,'pages/404.html')

  proveedoresList = Proveedor.objects.filter(empresa__id__contains=empresaId)
  print(proveedoresList)
  context = {}

  context["tieneProveedores"] = True
  if(len(proveedoresList)==0):
    context["tieneProveedores"] = False

  context["list"] = proveedoresList
  context["empresa"] = {"empresa":empresa, "id":empresaId}
  context["business_id"] = empresaId
  return render(request,'pages/proveedor/list.html',context)
  
def deleteProveedor(request):
  proveedorId = request.GET.get('proveedor') 
  if(proveedorId == None):
    return render(request,'pages/404.html')
  proveedor = Proveedor.objects.get(id=proveedorId)
  if(proveedor == None):
    return render(request,'pages/404.html')
  proveedor.delete()
  empresaId = str(proveedor.empresa.id)
  return redirect('/proveedor?empresa='+empresaId)

def seeProveedor(request):
  proveedorId = request.GET.get('proveedor') 
  if(proveedorId == None):
    return render(request,'pages/404.html')
  proveedor = Proveedor.objects.get(id=proveedorId)
  if(proveedor == None):
    return render(request,'pages/404.html')
  socialMediaForm  = SocialMediaFormset(
    prefix="proveedorSocial",
    queryset=proveedor.redes_proveedor.all()
  )
  socialMediaRepresentanteForm = SocialMediaFormset(
    prefix="representanteSocial",
    queryset=proveedor.redes_representante.all(),
  )
  context = {
    "proveedor" :proveedor,
    "business_id": proveedor.empresa.id,
    "socialMedia":socialMediaForm,
    "socialMediaRepresentante":socialMediaRepresentanteForm,
    "list_link":'/proveedor?empresa='+str(proveedor.empresa.id)
  }
  return render(request,'pages/proveedor/read.html', context)

##otras funciones
def findEmpresa(empresaId):
  empresa = Empresa.objects.get(id=empresaId)
  return empresa

lab_ati/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

lab_ati/templates/pages/proveedor/create-update.html
{% extends "base.html" %} 
{% load i18n %}
{% block content %} 
{% include "../../common/navigation-bar.html" with back_link=request.META.HTTP_REFERER list_link=list_link %}
{% if data.update == True %}
<h2>{% trans "Modificar proveedor" %} {{data.proveedor.nombre}}</h2>
{% else %}
<h2>{% trans "Registro de Proveedor para empresa" %} {{ data.empresa.nombre}}</h2>
{% endif %}

<div class="container col-8 mx-auto" id="form-box">
  {% include "pages/proveedor/formAuto.html" with data=data%}
</div>

{% endblock content %}
{% block inline_javascript %}
  <script>
    window.addEventListener('DOMContentLoaded', () => {
      new SocialMediaController("proveedorSocial");
      // Aqui iria el id de las redes sociales del representante
      new SocialMediaController("representanteSocial");
    });
    </script>
{% endblock %}

lab_ati/templates/pages/proveedor/formAuto.html
{% load i18n %}
{% if data.update == True %}
<form
  class="container d-grid gap-3 pb-4"
  enctype="multipart/form-data"
  action="/proveedor/modificar?proveedor={{data.proveedor.id}}" 
  method="post"
>
{% else %}
<form
  class="container d-grid gap-3 pb-4"
  enctype="multipart/form-data"
  action="/proveedor/crear?empresa={{data.empresa.id}}" 
  method="post"
>
{% endif %}
  {% csrf_token %}
  <div class="section-box">
    <p class="fw-bold fs-5">{% trans 'Información del proveedor' %}</p>
    {% for campo in data.formulario %}
    {% if campo.label != 'Empresa' and campo.label != 'Business'  %}
    {% if campo.label|slice:"-13:" != "representante" and campo.label|slice:':15' != 'Representatives'%}
    <section class="row mb-3">
      <section class="col input-group">
      <label class="input-group-text">{{campo.label}}</label>
        <input
        type="{{campo.field.widget.input_type}}"
        class="form-control"
        name="{{campo.name}}"
        placeholder="{{campo.label}}"
        value="{{data.proveedor|get_item:campo.name}}"
        Required
        />
      </section>
    </section>

    {% endif %}
    {% endif %}
    {% endfor %}
    <p>{% trans 'Redes sociales' %}</p>
    {% include "common/social_media_form.html" with socialm_formset=data.socialMedia%}
    <br/>
    <p class="fw-bold fs-5">{% trans 'Información del representante' %}</p>

    {% for campo in data.formulario %}
    {% if campo.label != 'Empresa' and campo.label != 'Business'%}
    {% if campo.label|slice:"-13:" == "representante" or campo.label|slice:':15' == 'Representatives'%} 
    <section class="row mb-3">
      <section class="col input-group">
        <label class="input-group-text">{{campo.label}}</label>
        <input
        type="{{campo.field.widget.input_type}}"
        class="form-control"
        name="{{campo.name}}"
        placeholder="{{campo.label}}"
        value="{{data.proveedor|get_item:campo.name}}"
        Required
      />
      </section>
    </section>
    {% endif %}
    {% endif %}
    {% endfor %}
  
    <p>{% trans 'Redes sociales' %}</p>
    {% include "common/social_media_form.html" with socialm_formset=data.socialMediaRepresentante%}
    <div class="mb-3" style="display: none;">
      <label class="form-label">Empresa</label>
      <input
        type="select"
        class="form-control"
        name="empresa"
        placeholder="Empresa"
      />
      <select name="empresa" id="id_empresa">
        <option value="{{data.empresa.id}}" selected></option>
      </select>
      
    </div>
    
  </div>
  

  <div class="d-grid gap-2 col-6 mx-auto form-button-box">
    <button class="btn btn-primary" type="submit">{% trans "Guardar" %}</button>
  </div>
</form>

lab_ati/templates/pages/proveedor/list.html
{% extends "base.html" %} 
{% load i18n %}
{% block content %}

<section class="general-container ">
  <h2 class="text-center pb-4">{% trans 'Lista de proveedores de' %} {{empresa.empresa.nombre}}</h2>
  <section class="container d-grid gap-3 pb-4">
    <section class="row">
      {% if tieneProveedores %}
      <section class="d-flex justify-content-between mb-2">
        
        <h2>{% trans 'Gestiona proveedores' %}</h2>
        <a href="/proveedor/crear?empresa={{empresa.id}}">
          <button type="button" class="btn btn-primary">
            <i class="bi bi-plus-lg"></i>
          </button>
        </a>
      </section>
      
      <table class="table table-success table-striped">
        <thead>
          <tr>
            <th>{% trans 'Nombre' %}</th>
            <th>{% trans 'Id Tributaria' %}</th>
            <th>{% trans 'Acciones' %}</th>
          </tr>
        </thead>
        <tbody>
          {% for item in list %}
          <tr>
            <td>
              {{ item.nombre }}            
            </td>
            <td>
              {{ item.id_tributaria }}            
            </td>
            <td class="d-flex">
              <a href="/proveedor/ver?proveedor={{item.id}}">
                <button type="button" class="mx-2 btn btn-info">
                  <i class="bi bi-search"></i>
                </button>
              </a>
              <a href="/proveedor/modificar?proveedor={{item.id}}">
                <button type="button" class="mx-2 btn btn-primary">
                  <i class="bi bi-pencil-square"></i>
                </button>
              </a>
              <a href="/proveedor/eliminar?proveedor={{item.id}}">
                <button type="button" class="mx-2 btn btn-danger">
                  <i class="bi bi-person-x"></i>
                </button>
              </a>
            </td>
          </tr>   
          {% endfor %}
        </tbody>
      </table>
      {% else %}
      <section class="d-flex justify-content-between mb-2">
        <h2>{% trans 'No se tienen proveedores registrados' %}</h2>
        <a href="/proveedor/crear?empresa={{empresa.id}}">
          <button type="button" class="btn btn-primary">
            <i class="bi bi-plus-lg"></i>
          </button>
        </a>
      </section>
      {% endif %}
    </section>
  </section>
  
</section>



{% endblock content %}

lab_ati/templates/pages/proveedor/read.html
{% extends "base.html" %} 
{% load i18n %}
{% block content %}
<section class="general-container w-100">
  {% include "../../common/navigation-bar.html" with back_link=request.META.HTTP_REFERER list_link=list_link %}
  <h2 class="text-center pb-4">{% trans 'Información del proveedor' %}</h2>
  <div class="container col-10 mx-auto">
    <h5>{% trans 'Proveedor' %}</h5>
    <table class="table">
      <tbody>
        <tr>
          <td>{% trans 'Nombre' %}</td>
          <td>{{proveedor.nombre}}</td>
        </tr>
        <tr>
          <td>{% trans 'Servicio que proporciona' %}</td>
          <td>{{proveedor.servicio_proporciona}}</td>
        </tr>
        <tr>
          <td>{% trans 'Teléfono' %}</td>
          <td>{{proveedor.tlf}}</td>
        </tr>
        <tr>
          <td>{% trans 'País' %}</td>
          <td>{{proveedor.pais}}</td>
        </tr>
        <tr>
          <td>{% trans 'Ciudad o provincia' %}</td>
          <td>{{proveedor.ciudad}}</td>
        </tr>
        <tr>
          <td>{% trans 'Dirección' %}</td>
          <td>{{proveedor.direccion}}</td>
        </tr>
        <tr>
          <td>{% trans 'Correo electrónico' %}</td>
          <td>{{proveedor.email}}</td>
        </tr>
        <tr>
          <td>{% trans 'Pagina web' %}</td>
          <td>{{proveedor.web_site}}</td>
        </tr>
      </tbody>
    </table>
  </div>
  
 
  <div class="container col-10 mx-auto">
    <h6>{% trans 'Redes sociales' %}</h6>
    <table class="table">
      <tbody>
        {% for redSocial in socialMedia %}
        {% if redSocial.nombre.value != None %}
        <tr>
          <td>{{redSocial.nombre.value}}</td>
          <td>{{redSocial.valor.value}}</td>
        </tr>
        {% endif %}
        
        {% endfor %}
      </tbody>
    </table>
  </div>

  <br/>
  
  <div class="container col-10 mx-auto">
    <h5>{% trans 'Representante' %}</h5>
    <table class="table">
      <tbody>
        <tr>
          <td>{% trans 'Nombre' %}</td>
          <td>{{proveedor.representante}}</td>
        </tr>
        <tr>
          <td>{% trans 'Cargo' %}</td>
          <td>{{proveedor.cargo}}</td>
        </tr>
        <tr>
          <td>{% trans 'Correo electrónico' %}</td>
          <td>{{proveedor.email_representante}}</td>
        </tr>
        <tr>
          <td>{% trans 'Correo electrónico personal' %}</td>
          <td>{{proveedor.email_personal_representante}}</td>
        </tr>
        <tr>
          <td>{% trans 'Teléfono' %}</td>
          <td>{{proveedor.tlf_representate}}</td>
        </tr>
        <tr>
          <td>{% trans 'Teléfono local' %}</td>
          <td>{{proveedor.tlf_local}}</td>
        </tr>
        <tr>
          <td>{% trans 'País de residencia' %}</td>
          <td>{{proveedor.pais_representante}}</td>
        </tr>
      </tbody>
    </table>
  </div>

  
  <div class="container col-10 mx-auto">
    <h6>{% trans 'Redes sociales' %}</h6>
    <table class="table">
      <tbody>
        {% for redSocial in socialMediaRepresentante %}
        {% if redSocial.nombre.value != None %}
        <tr>
          <td>{{redSocial.nombre.value}}</td>
          <td>{{redSocial.valor.value}}</td>
        </tr>
        {% endif %}
        
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="container col-10 mx-auto">
    <section class="d-flex justify-content-center">
      <a href="/proveedor/modificar?proveedor={{proveedor.id}}" class="mx-2">
          <button class="btn btn-primary">
              {% trans 'Editar' %}
          </button>
      </a>
      <a href="/proveedor/eliminar?proveedor={{proveedor.id}}" class="mx-2">
          <button class="btn btn-danger">
              {% trans 'Eliminar' %}
          </button>
      </a>
  </section>
  </div>
</section>
<br/>
  

{% endblock content %}