config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="empresa:business-list"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('i18n/', include('django.conf.urls.i18n')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lab_ati.users.urls", namespace="users")), 
    path("proveedor/", include("lab_ati.proveedor.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("business/", include("lab_ati.cliente.urls")),
    # Business urls
    path("business/", include("lab_ati.empresa.urls", namespace="business")),
    # Employee urls

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    #path('proveedor/crear', createProveedor, name='createProveedor')
    
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lab_ati/cliente/urls.py
from django.urls import path
from lab_ati.cliente.views import (
    clientes,
    ver_cliente,
    crear_cliente,
    eliminar_cliente, 
    editar_cliente
    )

urlpatterns = [
    path('<slug:business_id>/clients/', clientes, name='clients'),
    path('<slug:business_id>/clients/create', crear_cliente, name='create-client'),
    path('<slug:business_id>/clients/<slug:id>', ver_cliente, name='detail-client'),
    path('<slug:business_id>/clients/delete/<slug:id>', eliminar_cliente, name='delete-client'),
    path('<slug:business_id>/clients/edit/<slug:id>', editar_cliente, name='edit-client')
]

lab_ati/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path("", views.BusinessListView.as_view(), name="business-list"),
    path("create", views.CreateBusinessView.as_view(), name="create-business"),
    path("details/<slug:pk>", views.BusinessDetailsView.as_view(), name="business-details"),
    path("edit/<slug:pk>", views.EditBusinessView.as_view(), name="edit-business"),
    path("delete/<slug:pk>", views.DeleteBusinessView.as_view(), name="delete-business"),
    path("<slug:business_id>/employees/create", views.CreateEmployeeView.as_view(), name="create-employee"),
    path("<slug:business_id>/employees/edit/<slug:pk>", views.EditEmployeeView.as_view(), name="edit-employee"),
    path("<slug:business_id>/employees/", views.ListEmployeeView.as_view(), name="list-employee"),
    path("<slug:business_id>/employees/delete/<slug:pk>", views.DeleteEmployeeView.as_view(), name="delete-employee"),
    path("<slug:business_id>/employees/<slug:pk>", views.DetailEmployeeView.as_view(), name="detail-employee"),
]

lab_ati/users/urls.py
from django.urls import path

from lab_ati.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lab_ati/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lab_ati.cliente.models import Cliente
from lab_ati.cliente.forms import ClienteForm
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.empresa.models import SocialMedia
from lab_ati.utils.social_media import add_social_media
from django.urls import reverse

def clientes(request, business_id):
    context = {}
    context['business_id'] = business_id
    clientes = Cliente.objects.filter(empresa__id__contains = business_id)
    context['clientes'] = clientes
    return render(request, 'pages/clientes/index.html', context)

def ver_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    context['form'] = ClienteForm(request.POST or None, instance=cliente)
    context['social_medias'] = cliente.redes_sociales.all()
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    return render(request, 'pages/clientes/verCliente.html', context)

def crear_cliente(request, business_id):
    context = {}
    context['business_id'] = business_id
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST)
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)
        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return render(request, 'pages/clientes/crear.html', context)


def eliminar_cliente(request, id, business_id):
    cliente = Cliente.objects.get(id = id)
    cliente.delete()
    context = {}
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return redirect('clients', business_id = business_id)

def editar_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid() and request.POST:
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST, queryset=savedForm.redes_sociales.all())
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)

        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=cliente.redes_sociales.all())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context["editing_social"] = True

    return render(request, 'pages/clientes/editar.html', context)

lab_ati/empresa/views.py
from django.http.response import Http404
from django.urls.base import reverse_lazy

from django.views.generic import UpdateView, CreateView, ListView, DeleteView, DetailView, TemplateView
from .forms import CreateBusinessForm, CreateEmployeeForm, SocialMediaFormset
from lab_ati.empresa.models import Empleado, Empresa, SocialMedia
from django.urls import reverse
from django.utils.translation import gettext as _
from django.core import exceptions
from django.shortcuts import render
from lab_ati.utils.social_media import add_social_media
from django.urls import reverse

# Create your views here.
class BusinessListView(ListView):

    template_name = "pages/business/list.html"
    model = Empresa
    paginate_by = 10


    def get_queryset(self):
        queryset = Empresa.objects.all()
        return queryset

class DeleteBusinessView(DeleteView):
    template_name = "pages/business/delete.html"
    model = Empresa

    def get_success_url(self):
        return reverse('empresa:business-list')

class CreateBusinessView(CreateView):
    template_name = "pages/business/create.html"
    model = Empresa
    form_class = CreateBusinessForm

    def get_success_url(self):
        return reverse(
            "empresa:edit-business",
            kwargs={
                "pk": self.object.pk,
            }
        )

    def post(self, request, *args, **kwargs):
        self.object = None

        self.social_media_formset = SocialMediaFormset(data = self.request.POST)
        
        #Call parent class post
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        if not self.social_media_formset.is_valid():
            return self.form_invalid(form)
        
        res = super().form_valid(form)
        # Add social media to Empresa
        add_social_media(self.object, self.social_media_formset)
        return res

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                socialm_formset=self.social_media_formset
            )
        )

    def get_context_data(self, **kwargs):
        # Queryset vacio porque vamos a crear una empresa nuevo
        context = super().get_context_data(**kwargs)
        context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
        return context

class EditBusinessView(UpdateView):
    template_name = "pages/business/create.html"
    model = Empresa
    form_class = CreateBusinessForm
    pk_url_kwarg = "pk"

    def get_success_url(self):
        return reverse(
            "empresa:edit-business",
            kwargs={
                "pk": self.object.pk
            }
        )
    
    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        self.social_media_formset = SocialMediaFormset(
            data=self.request.POST,
            queryset=self.object.redes_sociales.all()
        )
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):

        if not self.social_media_formset.is_valid():
            return self.media_form_invalid(form)

        # Update and add social media
        add_social_media(self.object, self.social_media_formset)

        res = super().form_valid(form)
        return res

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                socialm_formset=self.social_media_formset
            )
        )

    def media_form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                socialm_formset=self.social_media_formset
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["socialm_formset"] = SocialMediaFormset(
            queryset=self.object.redes_sociales.all()
        )
        context["editing_social"] = True
        context["business_id"] = self.object.id
        return context


class BusinessDetailsView(DetailView):
    template_name = "pages/business/detail.html"
    model = Empresa

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["business_id"] = self.object.id
        return context
class CreateEmployeeView(CreateView):
    template_name = "pages/employees/create.html"
    model = Empleado
    form_class = CreateEmployeeForm

    def get_success_url(self):
        return reverse(
            "empresa:edit-employee",
            kwargs={
                "business_id": self.empresa.id,
                "pk": self.object.pk,
            },
        )
    def get_empresa(self):

        # Validate that Empresa exists
        try:
            empresa = Empresa.objects.get(id=self.kwargs.get("business_id"))
        except (Empresa.DoesNotExist, exceptions.ValidationError):
            raise Http404(_("La empresa no existe"))

        return empresa

    def post(self, request, *args, **kwargs):
        self.object = None

        # Validate that Empresa exists
        self.empresa = self.get_context_data()["empresa"]

        self.social_media_formset = SocialMediaFormset(data=self.request.POST)

        # Call parent class post
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        # Override form valid method to add socialmedia
        # functionality

        if not self.social_media_formset.is_valid():
            return self.form_invalid(form)

        res = super().form_valid(form)
        # Add social media to Empleado
        add_social_media(self.object, self.social_media_formset)
        return res

    def form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                socialm_formset=self.social_media_formset
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_id'] = self.kwargs['business_id']
        context["empresa"] = self.get_empresa()
        context["business_id"] = context["empresa"].id
        # Header
        context["list_link"] = reverse("empresa:list-employee", kwargs={"business_id": context["empresa"].id} )
        context["back_link"] = context["list_link"]

        # Queryset vacio porque vamos a crear un empleado nuevo
        context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
        return context


class EditEmployeeView(UpdateView):
    template_name = "pages/employees/create.html"
    model = Empleado
    form_class = CreateEmployeeForm
    pk_url_kwarg = 'pk'

    def get_success_url(self):
        return reverse(
            "empresa:edit-employee",
            kwargs={
                "business_id": self.empresa.id,
                "pk": self.object.pk,
            },
        )

    def get_empresa(self):

        # Validate that Empresa exists
        try:
            empresa = Empresa.objects.get(id=self.kwargs.get("business_id"))
        except (Empresa.DoesNotExist, exceptions.ValidationError):
            raise Http404(_("La empresa no existe"))

        return empresa

    def post(self, request, *args, **kwargs):

        self.object = self.get_object()
        self.empresa = self.get_empresa()
        self.social_media_formset = SocialMediaFormset(
            data=self.request.POST,
            queryset=self.object.redes_sociales.all()
        )
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):

        if not self.social_media_formset.is_valid():
            return self.media_form_invalid(form)

        # Update and add social media
        add_social_media(self.object, self.social_media_formset)

        res = super().form_valid(form)
        return res

    def media_form_invalid(self, form):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                socialm_formset=self.social_media_formset
            )
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_id'] = self.kwargs['business_id']
        context["empresa"] = self.get_empresa()
        context["socialm_formset"] = SocialMediaFormset(
            queryset=self.object.redes_sociales.all()
        )
        context["editing_social"] = True

        context["list_link"] = reverse("empresa:list-employee", kwargs={"business_id": context["empresa"].id} )
        context["back_link"] = context["list_link"]

        return context

class ListEmployeeView(ListView):
    template_name = "pages/employees/list.html"
    model = Empleado
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_id'] = self.kwargs['business_id']
        return context

    def get_queryset(self):
        queryset = Empleado.objects.filter(empresa = self.kwargs['business_id'])
        return queryset


class DeleteEmployeeView(DeleteView):
    template_name = "pages/employees/delete.html"
    model = Empleado

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_id'] = self.kwargs['business_id']

        context["list_link"] = reverse("empresa:list-employee", kwargs={"business_id": context["business_id"]} )
        context["back_link"] = context["list_link"]
        return context

    def get_success_url(self):
        return reverse('empresa:list-employee', kwargs={ 'business_id': self.kwargs['business_id']})

class DetailEmployeeView(DetailView):
    template_name = "pages/employees/detail.html"
    model = Empleado

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['business_id'] = self.kwargs['business_id']

lab_ati/templates/pages/business/delete.html
{% extends "../../base.html" %}
{% load i18n %}

{% block content %}
<section class="general-container w-100 h-100">
    {% include "../../common/navigation-bar.html" %}
    <section class="w-100 d-flex flex-column justify-content-center align-items-center">
        <section class="rounded p-4 bg-white mt-4">
            <h2 class="text-center pb-4">{% trans "Borrar empresa" %}</h2>
            <form method="post">
                {% csrf_token %}
                <p> {% trans "¿Deseas borrar la empresa" %} {{ object.nombre }}?</p>
                <section class="w-100 d-flex justify-content-center">
                    <button class="mx-2 btn btn-danger">
                        {% trans "Borrar" %}
                    </button>

                    <a href="{% url 'empresa:business-list' %}">
                        <button class="btn btn-light" type="button">
                            {% trans "Cancelar" %}
                        </button>
                    </a>
                </section>
            </form>
        </section>
    </section>
</section>
{% endblock content %}
{% block inline_javascript %}
{% endblock %}

lab_ati/templates/pages/business/detail.html
{% extends "../../base.html" %}
{% load i18n %}

{% block content %}
<section>
    {% include "../../common/navigation-bar.html" %}
    <h2 class="text-center pb-4">{% trans "Información de la empresa" %}</h2>
    <section class="card">
        <section class="card-body">
            <p class="card-text"> {% trans 'Nombre' %}: {{ object.nombre }}</p>
            <p class="card-text"> {% trans 'Id Tributaria' %}: {{ object.id_tributaria }}</p>
            <p class="card-text"> {% trans 'País' %}: {{ object.pais }}</p>
            <p class="card-text"> {% trans 'Ciudad' %}: {{ object.ciudad }}</p>
            <p class="card-text"> {% trans 'Dirección' %}: {{ object.direccion }}</p>
            <p class="card-text"> {% trans 'Email' %}: {{ object.email }}</p>
            <p class="card-text"> {% trans 'Sitio Web' %}: {{ object.web_site }}</p>
            <p class="card-text"> {% trans 'Teléfono' %}: {{ object.telefono }}</p>
            <p class="card-text"> {% trans 'Whatsapp' %}: {{ object.whatsapp }}</p>
            <p class="card-text"> {% trans 'Servicio que le ofrecimos' %}: {{ object.servicio_ofrecido }}</p>
            <p class="card-text"> {% trans 'Servicio que proporciona' %}: {{ object.servicio_proporciona }}</p>
            <p class="card-text"> {% trans 'Frecuencia en que desea mantenerse informado' %}: {{ object.frecuencia }}</p>
            <p class="card-text"> {% trans 'Cursos de interés' %}: {{ object.curso_interes }}</p>
            {% if object.cliente_empresa %}
                <p class="card-text"> {% trans 'Cliente de empresa' %}: {{ object.cliente_empresa }}</p>
            {% endif %}
            <section class="d-flex justify-content-center">
                <a href="{% url 'empresa:edit-business' pk=object.id %}">
                    <button class="btn btn-primary">
                        {% trans 'Editar' %}
                    </button>
                </a>
                <a href="{% url 'empresa:delete-business' pk=object.id %}" class="mx-2">
                    <button class="btn btn-danger">
                        {% trans 'Eliminar' %}
                    </button>
                </a>
                <a href="{%url "clients" business_id=business_id%}" class="mx-2">
                    <button class="btn btn-warning">
                        {% trans 'Clientes' %}
                    </button>
                </a>
                <a href="{% url "listProveedor"%}?empresa={{business_id }}" class="mx-2">
                    <button class="btn btn-warning">
                        {% trans 'Proveedores' %}
                    </button>
                </a>
                <a href="{% url 'empresa:list-employee' business_id=object.id %}" class="mx-2">
                    <button class="btn btn-warning">
                        {% trans 'Empleados' %}
                    </button>
                </a>
                
            </section>
            
        </section>
    </section>
</section>
{% endblock %}

lab_ati/templates/pages/business/list.html
{% extends "../../base.html" %}
{% load i18n %}

{% block content %}
    <section>
        <h2 class="text-center pb-4"> {% trans "Empresas de la corporación X" %}<h2>
        <form method="POST" class="container d-grid gap-3 pb-4">
            {% csrf_token %}
            <section class="row">
                <section class="d-flex justify-content-between mb-2">
                    <h2>{% trans "Gestiona empresas" %}</h2>
                    <a href="{% url 'empresa:create-business' %}">
                        <button type="button" class="btn btn-primary">
                            <i class="bi bi-plus-lg"></i>
                        </button>
                    </a>
                </section>

                <table class="table table-success table-striped">
                    <thead>
                        <tr>
                            <th>
                                {% trans "Nombre" %}
                            </th>
                            <th>
                                {% trans "País" %}
                            </th>
                            <th>
                                {% trans "RIF" %}
                            </th>
                            <th>
                                {% trans "Acciones" %}
                            </th>
                        </tr>
                    </thead>

                    <tbody>
                        {% for business in object_list %}
                            <tr>
                                <td>
                                    {{ business.nombre }}
                                </td>
                                <td>
                                    {{ business.pais }}
                                </td>
                                <td>
                                    {{ business.id_tributaria }}
                                </td>
                                <td class="d-flex">
                                    <a href="{% url 'empresa:business-details' pk=business.id %}">
                                        <button type="button" class="me-2 btn btn-info">
                                            <i class="bi bi-search"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'empresa:edit-business' pk=business.id %}">
                                        <button type="button" class="mx-2 btn btn-primary">
                                            <i class="bi bi-pencil-square"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'empresa:delete-business' pk=business.id %}">
                                        <button type="button" class="mx-2 btn btn-danger">
                                            <i class="bi bi-x"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'clients' business_id=business.id %}">
                                        <button type="button" class="mx-2 btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Clientes' %}">
                                            <i class="bi bi-person"></i>
                                        </button>
                                    </a>
                                    <a href="{% url 'empresa:list-employee' business_id=business.id %}">
                                        <button type="button" class="mx-2 btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Empleados' %}">
                                            <i class="bi bi-person-check"></i>
                                        </button>
                                    </a>
                                    <a href="{%url "listProveedor"%}?empresa={{ business.id }}" >
                                        <button type="button" class="mx-2 btn btn-warning" data-bs-toggle="tooltip" data-bs-placement="top" title="{% trans 'Proveedores' %}">
                                            <i class="bi bi-briefcase"></i>
                                        </button>
                                    </a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <section class="d-flex justify-content-center w-100">
                    {% include "../../common/pagination.html" with is_paginated=is_paginated paginator=paginator page_obj=page_obj %}
                </section>
            </section>
        </form>
    </section>
{% endblock %}