config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView, RedirectView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path("", RedirectView.as_view(pattern_name="empresa:business-list"), name="home"),
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    path('i18n/', include('django.conf.urls.i18n')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("lab_ati.users.urls", namespace="users")), 
    path("proveedor/", include("lab_ati.proveedor.urls")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("business/", include("lab_ati.cliente.urls")),
    # Business urls
    path("business/", include("lab_ati.empresa.urls", namespace="business")),
    # Employee urls

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()


# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
    #path('proveedor/crear', createProveedor, name='createProveedor')
    
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

lab_ati/cliente/urls.py
from django.urls import path
from lab_ati.cliente.views import (
    clientes,
    ver_cliente,
    crear_cliente,
    eliminar_cliente, 
    editar_cliente
    )

urlpatterns = [
    path('<slug:business_id>/clients/', clientes, name='clients'),
    path('<slug:business_id>/clients/create', crear_cliente, name='create-client'),
    path('<slug:business_id>/clients/<slug:id>', ver_cliente, name='detail-client'),
    path('<slug:business_id>/clients/delete/<slug:id>', eliminar_cliente, name='delete-client'),
    path('<slug:business_id>/clients/edit/<slug:id>', editar_cliente, name='edit-client')
]

lab_ati/empresa/urls.py
from django.urls import path
from . import views

app_name = "empresa"

urlpatterns = [
    path("", views.BusinessListView.as_view(), name="business-list"),
    path("create", views.CreateBusinessView.as_view(), name="create-business"),
    path("details/<slug:pk>", views.BusinessDetailsView.as_view(), name="business-details"),
    path("edit/<slug:pk>", views.EditBusinessView.as_view(), name="edit-business"),
    path("delete/<slug:pk>", views.DeleteBusinessView.as_view(), name="delete-business"),
    path("<slug:business_id>/employees/create", views.CreateEmployeeView.as_view(), name="create-employee"),
    path("<slug:business_id>/employees/edit/<slug:pk>", views.EditEmployeeView.as_view(), name="edit-employee"),
    path("<slug:business_id>/employees/", views.ListEmployeeView.as_view(), name="list-employee"),
    path("<slug:business_id>/employees/delete/<slug:pk>", views.DeleteEmployeeView.as_view(), name="delete-employee"),
    path("<slug:business_id>/employees/<slug:pk>", views.DetailEmployeeView.as_view(), name="detail-employee"),
]

lab_ati/users/urls.py
from django.urls import path

from lab_ati.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

lab_ati/cliente/models.py
from django.db import models
from lab_ati.empresa.models import DirABC
from django.utils.translation import gettext_lazy as _

# Create your models here.

class ClientType(models.TextChoices):
    LABORA_EMPRESA = 'LE', _('Labora empresa')
    STUDENT = 'SO', _('Estudiante')
    OTHER = 'JR', _('Otro')

class Cliente(DirABC):

    nombre = models.TextField(_("Nombre y Apellido"))
    tipo = models.TextField(
        choices=ClientType.choices,
    )
    empcompany=models.TextField(_("Compañia/Organismo"))
    cargo=models.TextField(_("Cargo"))
    empresa=models.ForeignKey(
        to="empresa.Empresa",
        on_delete=models.CASCADE,
        related_name="clientes",
        verbose_name=_("Empresa"),
        null=True,
        blank=True,
    )
    personal_email=models.TextField(_("Email personal"))
    tlf_celular=models.TextField(_("Teléfono celular"))
    whatsapp=models.TextField(_("Whatsapp"))
    servicio_ofrecido = models.TextField(_("Servicio ofrecido"))
    curso_interes=models.TextField(_("Curso de interés"))
    frecuencia=models.TextField(_("Frecuencia con la que desea mantenerse informado"))

    def __str__(self):
        return f"{self.nombre} {self.tipo}"

lab_ati/cliente/forms.py
from django import forms
from lab_ati.cliente.models import Cliente

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = '__all__'

lab_ati/proveedor/forms.py
from django import forms
from .models import Proveedor

class ProveedorForm(forms.ModelForm):
  class Meta:
    model = Proveedor
    fields = '__all__'
 

lab_ati/cliente/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from lab_ati.cliente.models import Cliente
from lab_ati.cliente.forms import ClienteForm
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.empresa.models import SocialMedia
from lab_ati.utils.social_media import add_social_media
from django.urls import reverse

def clientes(request, business_id):
    context = {}
    context['business_id'] = business_id
    clientes = Cliente.objects.filter(empresa__id__contains = business_id)
    context['clientes'] = clientes
    return render(request, 'pages/clientes/index.html', context)

def ver_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    context['form'] = ClienteForm(request.POST or None, instance=cliente)
    context['social_medias'] = cliente.redes_sociales.all()
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    return render(request, 'pages/clientes/verCliente.html', context)

def crear_cliente(request, business_id):
    context = {}
    context['business_id'] = business_id
    form = ClienteForm(request.POST or None)
    if form.is_valid():
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST)
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)
        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=SocialMedia.objects.none())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return render(request, 'pages/clientes/crear.html', context)


def eliminar_cliente(request, id, business_id):
    cliente = Cliente.objects.get(id = id)
    cliente.delete()
    context = {}
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context['business_id'] = business_id
    return redirect('clients', business_id = business_id)

def editar_cliente(request, id, business_id):
    context = {}
    context['business_id'] = business_id
    cliente = Cliente.objects.get(id = id)
    form = ClienteForm(request.POST or None, instance=cliente)
    if form.is_valid() and request.POST:
        savedForm = form.save()
        social_media_formset = SocialMediaFormset(data=request.POST, queryset=savedForm.redes_sociales.all())
        if social_media_formset.is_valid():
            add_social_media(savedForm, social_media_formset)

        return redirect('clients', business_id = business_id)
    context['form'] = form
    context["socialm_formset"] = SocialMediaFormset(queryset=cliente.redes_sociales.all())
    context["list_link"] = reverse("clients", kwargs={"business_id": business_id} )
    context["editing_social"] = True

    return render(request, 'pages/clientes/editar.html', context)

lab_ati/proveedor/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Proveedor
from .forms import ProveedorForm
#from ..empresa.models import Empresa, SocialMedia 
from django.template.defaulttags import register
from lab_ati.empresa.models import Empresa, SocialMedia
from lab_ati.empresa.forms import SocialMediaFormset
from lab_ati.utils.social_media import add_social_media

@register.filter
def get_item(objectList, key):
  if objectList == "":
    return ""
  return getattr(objectList,key)

def createProveedor(request):
  if request.method == 'GET': 
    empresaId = request.GET.get('empresa') 
    if(empresaId == None):
      return render(request,'404.html')
    empresa = Empresa.objects.get(id=empresaId)
    if(empresa == None):
      return render(request,'404.html')
    #print(empresa)
    formularioProveedor = ProveedorForm(request.GET)
    context = {}
    proveedorSocialMedia = SocialMediaFormset(
        prefix="proveedorSocial",
        queryset=SocialMedia.objects.none()
    )
    socialMediaRepresentanteForm = SocialMediaFormset(
        queryset=SocialMedia.objects.none(),
        prefix="representanteSocial"
    )
    #socialMediaRepresentanteForm = SocialMediaFormset(queryset=SocialMedia.objects.none())
    #print(proveedorSocialMedia)
    context = {
      "data":{
        "empresa":empresa,
        "update":False, 
        "formulario":formularioProveedor,
        "socialMedia" : proveedorSocialMedia,
        "socialMediaRepresentante": socialMediaRepresentanteForm
      },
      "list_link":'/proveedor?empresa='+str(empresaId)
      }
    return render(request,'pages/proveedor/create-update.html', context)

  elif request.method == 'POST':
    empresaId = request.GET.get('empresa') 
    if(empresaId == None):
      return render(request,'404.html')  
    empresa = Empresa.objects.get(id=empresaId)
    if(empresa == None):
      return render(request,'404.html')
    formularioProveedor = ProveedorForm(request.POST)
    #print(formularioProveedor)
    social_media_formset = SocialMediaFormset(data=request.POST, prefix="proveedorSocial")
    redes_representante_formset = SocialMediaFormset(data=request.POST, prefix="representanteSocial")
    #print(social_media_formset)
    if formularioProveedor.is_valid() and social_media_formset.is_valid() and redes_representante_formset.is_valid():
      #print('is valid!')
      proveedorSaved = formularioProveedor.save()
      # Añadir las redes sociales del proveedor
      add_social_media(proveedorSaved,social_media_formset, belongs_to="redes_proveedor")
      # Añadir las redes sociales del representante
      add_social_media(proveedorSaved, redes_representante_formset, belongs_to="redes_representante")
      return redirect('/proveedor?empresa='+empresaId)
    return redirect('/proveedor/crear?empresa='+empresaId)
    
def updateProveedor(request):
  if request.method == 'GET':
    proveedorId = request.GET.get('proveedor')
    print('proveedor id: ', proveedorId)
    if(proveedorId == None):
      return render(request,'404.html')
    proveedor = Proveedor.objects.get(id=proveedorId)
    if(proveedor == None):
      return render(request,'404.html') 
    print(proveedor)
    formularioProveedor = ProveedorForm(request.POST or request.GET)
    socialMediaForm  = SocialMediaFormset(
        prefix="proveedorSocial",
        queryset=proveedor.redes_proveedor.all()
    )
    socialMediaRepresentanteForm = SocialMediaFormset(
        prefix="representanteSocial",
        queryset=proveedor.redes_representante.all(),
    )

    context = {
      "business_id": proveedor.empresa.id,
      "data":{
        "proveedor":proveedor,
        "empresa":{"id":proveedor.empresa.id},
        "update":True,
        "formulario":formularioProveedor,
        "socialMedia":socialMediaForm,
        "socialMediaRepresentante": socialMediaRepresentanteForm
      },
      "editing_social":True,
      "list_link":'/proveedor?empresa='+str(proveedor.empresa.id)
    }
    return render(request,'pages/proveedor/create-update.html',context)
  elif request.method == 'POST':
    proveedorId = request.GET.get('proveedor')
    print('proveedor id: ', proveedorId)
    if(proveedorId == None):
      return render(request,'404.html')
    oldProveedor = Proveedor.objects.get(id=proveedorId)
    if(oldProveedor == None):
      return render(request,'404.html')
    print(oldProveedor)
    formularioProveedor = ProveedorForm(request.POST, instance=oldProveedor)
    print(formularioProveedor)
    empresaId = str(oldProveedor.empresa.id)
    if formularioProveedor.is_valid():
      print('is valid!')
      proveedorSaved = formularioProveedor.save()
      social_media_formset = SocialMediaFormset(
        prefix="proveedorSocial",
        data=request.POST,
        queryset=proveedorSaved.redes_proveedor.all()
      )
      socialMediaRepresentanteForm = SocialMediaFormset(
        queryset=proveedorSaved.redes_representante.all(),
        data=request.POST,
        prefix="representanteSocial"
      )

      if social_media_formset.is_valid():
        add_social_media(proveedorSaved,social_media_formset, belongs_to="redes_proveedor")
      if socialMediaRepresentanteForm.is_valid():
        add_social_media(proveedorSaved,socialMediaRepresentanteForm, belongs_to="redes_representante")
    return redirect('/proveedor?empresa='+empresaId)


#listar proeedores de una emrpresa dada
def listProveedor(request):
  empresaId = request.GET.get('empresa')
  print(empresaId)
  if(empresaId == None):
    return render(request,'pages/404.html')

  empresa = findEmpresa(empresaId)
  print(empresa)
  if(empresa == None): #empresa no existe
    return render(request,'pages/404.html')

  proveedoresList = Proveedor.objects.filter(empresa__id__contains=empresaId)
  print(proveedoresList)
  context = {}

  context["tieneProveedores"] = True
  if(len(proveedoresList)==0):
    context["tieneProveedores"] = False

  context["list"] = proveedoresList
  context["empresa"] = {"empresa":empresa, "id":empresaId}
  context["business_id"] = empresaId
  return render(request,'pages/proveedor/list.html',context)
  
def deleteProveedor(request):
  proveedorId = request.GET.get('proveedor') 
  if(proveedorId == None):
    return render(request,'pages/404.html')
  proveedor = Proveedor.objects.get(id=proveedorId)
  if(proveedor == None):
    return render(request,'pages/404.html')
  proveedor.delete()
  empresaId = str(proveedor.empresa.id)
  return redirect('/proveedor?empresa='+empresaId)

def seeProveedor(request):
  proveedorId = request.GET.get('proveedor') 
  if(proveedorId == None):
    return render(request,'pages/404.html')
  proveedor = Proveedor.objects.get(id=proveedorId)
  if(proveedor == None):
    return render(request,'pages/404.html')
  socialMediaForm  = SocialMediaFormset(
    prefix="proveedorSocial",
    queryset=proveedor.redes_proveedor.all()
  )
  socialMediaRepresentanteForm = SocialMediaFormset(
    prefix="representanteSocial",
    queryset=proveedor.redes_representante.all(),
  )
  context = {
    "proveedor" :proveedor,
    "business_id": proveedor.empresa.id,
    "socialMedia":socialMediaForm,
    "socialMediaRepresentante":socialMediaRepresentanteForm,
    "list_link":'/proveedor?empresa='+str(proveedor.empresa.id)
  }
  return render(request,'pages/proveedor/read.html', context)

##otras funciones
def findEmpresa(empresaId):
  empresa = Empresa.objects.get(id=empresaId)
  return empresa

lab_ati/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

lab_ati/templates/pages/clientes/crear.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div>
        {% include "../../common/navigation-bar.html" %}
        <h2 class="text-center pb-4">
            {% trans "Crea a un cliente con información" %}
        </h2>
        {% include "pages/clientes/form.html" %}
    </div>
{% endblock content %}

lab_ati/templates/pages/clientes/editar.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div>
        {% include "../../common/navigation-bar.html" %}
        <h2 class="text-center pb-4">
            {% trans "Edita la información de un cliente" %}
        </h2>
        {% include "pages/clientes/form.html" %}
    </div>
{% endblock content %}

lab_ati/templates/pages/clientes/form.html
{% load i18n %}
<form enctype="multipart/form-data" method="post"  class="container d-grid gap-3 pb-4">
    {% csrf_token %}
    <div class="row">
        {% for field in form %}
            {% if field.name == 'empresa' %}
            <div style="display: none;" class="col-0">
            {% else %}
            <div class="col-6" style="margin-bottom: 15px;">
            {% endif %}
                <div class="col input-group">

                    {% if field.name == 'tipo' %}
                        <label class="input-group-text">{% trans "Tipo" %}</label>
                        <select 
                            class="form-select" 
                            aria-label="Default select example"
                            name="{{ field.name }}"
                            placeholder="{{ field.label }}" 
                            value="{{ field.value | default:'' }}"
                        >
                            <option value="LE" {% if field.value == 'LE' %} selected {% endif %}>
                                <h5>{% trans "Labora empresa" %}</h5>
                            </option>
                            <option value="SO" {% if field.value == 'SO' %} selected {% endif %}>
                                <h5>{% trans "Estudiante" %}</h5>
                            </option>
                            <option value="JR" {% if field.value == 'JR' %} selected {% endif %}>
                                <h5>{% trans "Otro" %}</h5>
                            </option>
                        </select>
                    {% else %}
                        <label class="input-group-text">{{ field.label }}</label>
                        <input 
                            type="{{ field.widget.input_type }}"
                            class="form-control" 
                            name="{{ field.name }}"
                            aria-describedby="helpId" 
                            placeholder="{{ field.label }}"
                            {% if field.name == 'empresa' %}
                                value="{{ business_id }}"
                            {% else %}
                                value="{{ field.value | default:'' }}"
                            {% endif %}
                            Required
                        >
                    {% endif %}
                    <span class="text-danger text-xs mx-2">
                        {{ field.errors }}
                    </span>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col input-group">
            <h5>{% trans "Redes Sociales" %}</h5>
            <ul class="list-group list-group w-100" id="socialNetworkList" ></ul>
        </div>
    </div>
    <div class="row">
        <div class="col input-group">
            {% include "common/social_media_form.html" with socialm_formset=socialm_formset%}
        </div>
    </div>
    <div class="row">
        <div class="col input-group">
            <input 
                class="btn btn-primary"
                type="submit"
                value={% trans "Enviar" %}
            >
        </div>
    </div>
</form>
{% block inline_javascript %}
    <script>
        window.addEventListener('DOMContentLoaded', () => {
            new SocialMediaController();
        });
    </script>
{% endblock %}

lab_ati/templates/pages/clientes/index.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="general-container">
        <div class="container d-grid gap-3 pb-4">
            <h2 class="text-center pb-4">{% trans "Lista de clientes" %}</h2>
            <div class="d-flex justify-content-between mb-2">
                <h2>{% trans "Gestiona clientes" %}</h2>
                <a  href="{% url 'create-client' business_id=business_id %}">
                    <button type="button" class="btn btn-primary">
                        <i class="bi bi-plus-lg"></i>
                    </button>
                </a>
            </div>
            <div class="row">
                <table class="table table-success table-striped">
                    <thead>
                        <tr>
                            <th>{% trans 'Nombre completo' %}</th>
                            <th>{% trans 'Tipo' %}</th>
                            <th>{% trans 'País' %}</th>
                            <th>{% trans 'Acciones' %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for cliente in clientes %}
                        <tr>
                            <td>{{ cliente.nombre }}</td>
                            <td>{{ cliente.get_tipo_display }}</td>
                            <td>{{ cliente.pais }}</td>
                            <td class="d-flex">
                                <a href="{% url 'detail-client' business_id=business_id id=cliente.id %}" >
                                    <button type="button" class="mx-2 btn btn-info">
                                        <i class="bi bi-search"></i>
                                    </button>
                                </a>
                                <a href="{% url 'edit-client' business_id=business_id id=cliente.id %}">
                                    <button type="button" class="mx-2 btn btn-primary">
                                        <i class="bi bi-pencil-square"></i>
                                    </button>
                                </a>
                                <a href="{%  url 'delete-client' business_id=business_id id=cliente.id %}">
                                    <button type="button" class="mx-2 btn btn-danger">
                                        <i class="bi bi-person-x"></i>
                                    </button>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock content %}

lab_ati/templates/pages/clientes/verCliente.html
{% extends "base.html" %}
{% load i18n %}
{% block content %}
    <div class="container">
        {% include "../../common/navigation-bar.html" %}
        <h2 class="text-center pb-4">{% trans "Información del cliente" %}</h2>
        <a class="btn btn-primary" href="{% url 'clients' business_id=business_id %}">Volver</a>
        {% csrf_token %}
        <div class="row">
            {% for field in form %}
                {% if field.name == 'empresa' %}
                <div style="display: none;">
                {% else %}
                <div class="col-6">
                {% endif %}
                    <label class="form-label">{{ field.label }}:</label>
                    <input 
                        type="{{ field.field.widget.input_type }}"
                        class="form-control" 
                        name="{{ field.name }}"
                        aria-describedby="helpId" 
                        placeholder="{{ field.label }}"
                        value="{{ field.value | default:'' }}"
                        disabled
                    > 
                </div>
            {% endfor %}
            <div class="row">
                <div class="col input-group">
                    <h5>{% trans "Redes Sociales" %}</h5>
                    <ul class="list-group list-group w-100" id="socialNetworkList" ></ul>
                </div>
            </div>
            <div class="row">
                {% for social_media in social_medias %}
                    <div class="col-6">
                        <label class="form-label">{{ social_media.nombre }}:</label>
                        <input 
                            type="{{ field.field.widget.input_type }}"
                            class="form-control" 
                            name="{{ field.name }}"
                            aria-describedby="helpId" 
                            placeholder="{{ field.label }}"
                            value="{{ social_media.valor }}"
                            disabled
                        > 
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock content %}